services:
  - type: web 
    plan: free
    name: cf-bet-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT 
        value: 3000
  - type: web 
    plan: free
    name: cf-bet-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT 
        value: 5000

